Failed to insert data into sqlite table table cnn has no column named awp_perturb_input
Traceback (most recent call last):
  File "/home/jbu/BPTT-Lipschitzness/datajuicer/database.py", line 92, in insert
    c.execute(insert)
sqlite3.OperationalError: table cnn has no column named awp_perturb_input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 37, in <module>
    run(models, "train", n_threads=flags.n_threads, run_mode=run_mode)("{*}")
  File "/home/jbu/BPTT-Lipschitzness/datajuicer/utils.py", line 102, in <lambda>
    return lambda *args, **kwargs: _runner(grid, *args, **kwargs)
  File "/home/jbu/BPTT-Lipschitzness/datajuicer/utils.py", line 93, in _runner
    ret = [_run(copy.copy(data),func,list(args),kwargs) for data in grid]
  File "/home/jbu/BPTT-Lipschitzness/datajuicer/utils.py", line 93, in <listcomp>
    ret = [_run(copy.copy(data),func,list(args),kwargs) for data in grid]
  File "/home/jbu/BPTT-Lipschitzness/datajuicer/utils.py", line 72, in _run
    database.insert(db_file = os.path.join(cache_dir, "sessions.db"), table = func.table_name, row = row, primary_key = "session_id")
  File "/home/jbu/BPTT-Lipschitzness/datajuicer/database.py", line 97, in insert
    raise Exception
Exception
